# Generated by Django 5.0.6 on 2026-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_category_monthly_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
